source 'https://rubygems.org'

gem 'bundler'
gem 'dry-monads'
gem 'dry-types'
gem 'dry-validation'
gem 'json'
gem 'pg'
gem 'puma'
gem 'rack'
gem 'rackup'
gem 'sequel'
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'sinatra', '~> 4.1'
gem 'sinatra-contrib'

group :development, :test do
  gem 'database_cleaner-sequel'
  gem 'dotenv'
  gem 'pry'
  gem 'rack-test'
  gem 'rack-unreloader'
  gem 'rspec'
  gem 'rubocop'
end
