name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop -c .rubocop.yml app/

  rspec:
    name: Test
    runs-on: ubuntu-latest
    needs: rubocop
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ipchecker_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RACK_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/ipchecker_db_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -U postgres; do
            sleep 1
          done

      - name: Run migrations
        run: bundle exec sequel -m db/migrations $DATABASE_URL

      - name: Run RSpec
        run: bundle exec rspec
